
-- ----------------------------
-- ElasticSearch任务表
-- ----------------------------
DROP TABLE IF EXISTS WEBHOOK_RECORD;
CREATE TABLE WEBHOOK_RECORD (
  ID INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  TYPE VARCHAR(30) DEFAULT 'log' COMMENT 'type',
  TITLE VARCHAR(200) DEFAULT NULL COMMENT '标题',
  DESCR TEXT COMMENT '说明',
  REMARK TEXT COMMENT '备注',
  TG_ID VARCHAR(30) DEFAULT NULL COMMENT 'tg ID',
  MAIL_ADD VARCHAR(200) DEFAULT NULL COMMENT '邮箱地址',
  REPORTER CHAR(30) DEFAULT NULL COMMENT '报告人',
  IP VARCHAR(200) DEFAULT NULL COMMENT 'IP',
  STATUS VARCHAR(1) DEFAULT NULL COMMENT '执行状态（0成功 1失败 2错误）',
  MESSAGE TEXT COMMENT '执行信息',
  CREATE_TIME DATETIME NOT NULL COMMENT '建立时间',
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='webhook请求记录表';